# Generated by Django 4.2.7 on 2023-11-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=25)),
                ('asset_description', models.CharField(max_length=40)),
                ('base_location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=25)),
                ('contact', models.BigIntegerField()),
                ('work_location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='In_Out_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.asset')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.employee')),
            ],
        ),
    ]
