# Generated by Django 4.2.7 on 2023-11-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_out_log',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
